[book]
title = "vprogs: a based rollup on Kaspa"
authors = ["143672"]
language = "en"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
